all:
	javac Sorting.java
	javac Numbers.java
	javac Strings.java
	javac SalePerson.java
	javac WeeklySales.java
	javac Shape.java
	javac Square.java
	javac Rectangle.java
	javac Triangle.java
	javac Circle.java
	javac Shape2DApp.java

	javac Cone.java
	javac Cuboid.java
	javac Cylinder.java
	javac Pyramid.java
	javac Sphere.java
	javac Shape3DApp.java

clean:
	rm *.class
